<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEFzjdOk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEFzjdOk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEFzjdOk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEFzjdOk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEFzjdOk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'EFzjdOk',
    'container.build_id' => 'f8124ecc',
    'container.build_time' => 1532346804,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEFzjdOk');
